[package]
name = "deskodon-frontend"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
slint = "1.2"
thiserror = "1"
tracing = "0.1"
url = "2.4"

deskodon-lib = { path = "../lib" }

[build-dependencies]
slint-build = "1.2.0"
