[package]
name = "deskodon-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3.55"
log = "0.4"
serde-wasm-bindgen = "0.4"
thiserror = "1"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
wasm-logger = "0.2"
web-sys = "0.3.55"
url = { version = "2.3", features = ["serde"] }
seed = "0.9.2"

deskodon-types = { version = "0.1.0", path = "../types" }

