[package]
name = "deskodon-frontend"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
slint.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true

deskodon-lib = { path = "../lib" }

[build-dependencies]
slint-build = "1.2.0"
