import { Button, VerticalBox , HorizontalBox} from "std-widgets.slint";

Progress := Rectangle {
    property <color> col1 : #2320db;
    property <color> col2 : #4fa4dd;

    property <float> animated : Math.mod(animation-tick()/2s, 1);
    background: animated < 0.25 ? @linear-gradient(90deg, col1 0%, col1 animated*4, col2 100%)
                : animated < 0.5  ? @linear-gradient(90deg, col2 0%, col1 animated*4 - 1, col1 100%)
                : animated < 0.75 ? @linear-gradient(90deg, col2 0%, col2 animated*4 - 2, col1 100%)
                :                   @linear-gradient(90deg, col1 0%, col2 animated*4 - 3, col2 100%);
}
