import { AboutSlint } from "std-widgets.slint";
import { Page } from "../page.slint";

export component AboutPage inherits Page {
    title: "About";
    description: "Are you curious now? Check out the docs and gettings start from the Github repository and the website https://slint.dev and try it yourself.";

    preferred-width: 100%;
    preferred-height: 100%;

    min-width: 1024px;
    min-height: 800px;

    AboutSlint {}
}

