import { Page } from "../page.slint";
import { LineEdit } from "std-widgets.slint";

export component AuthorizationUrlPage inherits Page {
    title: "Authorize";

    in-out property <string> url;

    preferred-width: 100%;
    preferred-height: 100%;

    VerticalLayout {
        spacing: 5px;

        instance := LineEdit {
            enabled: true;
            visible: true;
            read-only: true;
            font-size: 20px;
            width: 100%;

            text: root.url;
        }
    }
}
