import { Page } from "../page.slint";
import { LineEdit, Button } from "std-widgets.slint";

export component LoginPage inherits Page {
    title: "Login";

    in-out property <bool> enabled;

    callback login(string);
    callback notify_login_in_progress();
    notify_login_in_progress() => {
        logging_in_popup.show();
    }

    callback notify_login_succeeded();
    notify_login_succeeded() => {
        logging_in_popup.close();
    }

    preferred-width: 100%;
    preferred-height: 100%;

    logging_in_popup := PopupWindow {
        Rectangle {
            height:100%;
            width: 100%;
            background: yellow;

            text := LineEdit {
                enabled: true;
                font-size: 20px;
                placeholder-text: "Logging in...";
                read-only: true;
                width: 100%;
                height: 25px;
            }
        }
        x: 20px;
        y: 20px;
        height: 50px;
        width: 50px;
    }

    VerticalLayout {
        spacing: 5px;

        instance := LineEdit {
            enabled: true;
            font-size: 20px;
            placeholder-text: "Mastodon Instance URL";
            read-only: false;
            width: 100%;
            height: 25px;
        }

        login := Button {
            text: "Login";

            clicked => {
                root.login(instance.text)
            }
        }
    }
}



