import { Page } from "../page.slint";
import { LineEdit, Button } from "std-widgets.slint";

export component LoginPage inherits Page {
    title: "Login";

    in-out property <bool> enabled;

    callback login(string);

    preferred-width: 100%;
    preferred-height: 100%;

    VerticalLayout {
        spacing: 5px;

        instance := LineEdit {
            enabled: true;
            font-size: 20px;
            placeholder-text: "Mastodon Instance URL";
            read-only: false;
            width: 100%;
            height: 25px;
        }

        login := Button {
            text: "Login";

            clicked => {
                root.login(instance.text)
            }
        }
    }
}



