import { Button, HorizontalBox } from "std-widgets.slint";

import { Input } from "../input.slint";
import { Page } from "../page.slint";
import { ConnectBox } from "../connectbox.slint";

export component MainPage inherits Page {
    title: "Main";

    callback post_text_content <=> input.post_text_content;
    callback start_connecting <=> connect-box.start_connecting;

    HorizontalBox {
        preferred-width: 100%;
        preferred-height: 100%;

        min-width: 1024px;
        min-height: 800px;

        VerticalLayout {
            min-width: 100px;

            connect-box := ConnectBox {
                max-height: 50px;
            }

            input := Input {
                min-height: 50px;

                max-height: 200px;
            }

            Text { text: "Some Post"; }
            Text { text: "Some other Post"; }
            Text { text: "Some third Post"; }
        }
    }
}
