name: CI-format

on:
  push:
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    name: check-format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0
      - uses: dtolnay/rust-toolchain@1.65.0
        with:
          components: rustfmt
      - run: cargo fmt -- --check

